from setuptools import setup, find_packages

setup(
    name='TypeTruth',
    version='0.1.0',
    author='Bhaskar Tripathi',
    author_email='bhaskar.tripathi@gmail.com',
    long_description=open('README.md').read(),
    description='TypeTruth is a Python library that detects whether a text is written by a human or AI. Ideal for fact-checking and content validation in the age of AI content generators. Detect content generated by chatGPT, GPT4, GPT3.5, GPT3, Falcon, Vicuna, Stanford Alpaca, and LlAMA',
    long_description_content_type="text/markdown",
    url='https://github.com/bhaskatripathi/TypeTruth',
    packages=find_packages(),
    install_requires=[
        'requests',
        'numpy',
        'pandas',
        'matplotlib',
        'seaborn',
    ],
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
    ],
    python_requires='>=3.7',
)
